name: Deploy to gh-pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Builds production app
      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn build
      # Deploys to gh-pages
      - name: Install Dependencies and Build and Deploy
        run: |
          yarn install 
          yarn deploy
